# TCL File Generated by Component Editor 12.1sp1
# Thu Feb 11 11:52:52 MST 2016
# DO NOT MODIFY


# 
# ci_frame_done "ci_frame_done" v1.0
# Stephen Just 2016.02.11.11:52:52
# 
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module ci_frame_done
# 
set_module_property NAME ci_frame_done
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Custom Instructions"
set_module_property AUTHOR "Stephen Just"
set_module_property DISPLAY_NAME ci_frame_done
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ci_frame_done
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file ci_frame_done.vhd VHDL PATH custom_instructions/ci_frame_done.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point ci
# 
add_interface ci nios_custom_instruction end
set_interface_property ci clockCycle 0
set_interface_property ci operands 0
set_interface_property ci ENABLED true

add_interface_port ci ncs_ci_clk_en clk_en Input 1
add_interface_port ci ncs_ci_start start Input 1
add_interface_port ci ncs_ci_done done Output 1


# 
# connection point ext
# 
add_interface ext conduit end
set_interface_property ext associatedClock clock
set_interface_property ext associatedReset reset
set_interface_property ext ENABLED true

add_interface_port ext coe_ext_done done Input 1
add_interface_port ext coe_ext_trigger trigger Output 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true

add_interface_port clock ncs_ci_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset ncs_ci_reset reset Input 1

