# TCL File Generated by Component Editor 12.1sp1
# Sat Feb 13 14:47:51 MST 2016
# DO NOT MODIFY


# 
# colour_palette_shifter "Colour_Palette_Shifter" v1.0
# Stefan Martynkiw 2016.02.13.14:47:51
# 
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module colour_palette_shifter
# 
set_module_property NAME colour_palette_shifter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Video Pipeline"
set_module_property AUTHOR "Stefan Martynkiw"
set_module_property DISPLAY_NAME Colour_Palette_Shifter
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL colour_space_converter
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file colour_space_converter.vhd VHDL PATH colour_space_converter/colour_space_converter.vhd


# 
# parameters
# 
add_parameter BUFFER_START_ADDRESS STD_LOGIC_VECTOR 0
set_parameter_property BUFFER_START_ADDRESS DEFAULT_VALUE 0
set_parameter_property BUFFER_START_ADDRESS DISPLAY_NAME BUFFER_START_ADDRESS
set_parameter_property BUFFER_START_ADDRESS WIDTH 32
set_parameter_property BUFFER_START_ADDRESS TYPE STD_LOGIC_VECTOR
set_parameter_property BUFFER_START_ADDRESS UNITS None
set_parameter_property BUFFER_START_ADDRESS ALLOWED_RANGES 0:4294967295
set_parameter_property BUFFER_START_ADDRESS HDL_PARAMETER true
add_parameter BITS_PER_PIXEL INTEGER 8
set_parameter_property BITS_PER_PIXEL DEFAULT_VALUE 8
set_parameter_property BITS_PER_PIXEL DISPLAY_NAME BITS_PER_PIXEL
set_parameter_property BITS_PER_PIXEL TYPE INTEGER
set_parameter_property BITS_PER_PIXEL UNITS None
set_parameter_property BITS_PER_PIXEL ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BITS_PER_PIXEL HDL_PARAMETER true
add_parameter FRAME_WIDTH INTEGER 640
set_parameter_property FRAME_WIDTH DEFAULT_VALUE 640
set_parameter_property FRAME_WIDTH DISPLAY_NAME FRAME_WIDTH
set_parameter_property FRAME_WIDTH TYPE INTEGER
set_parameter_property FRAME_WIDTH UNITS None
set_parameter_property FRAME_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FRAME_WIDTH HDL_PARAMETER true
add_parameter FRAME_HEIGHT INTEGER 480
set_parameter_property FRAME_HEIGHT DEFAULT_VALUE 480
set_parameter_property FRAME_HEIGHT DISPLAY_NAME FRAME_HEIGHT
set_parameter_property FRAME_HEIGHT TYPE INTEGER
set_parameter_property FRAME_HEIGHT UNITS None
set_parameter_property FRAME_HEIGHT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FRAME_HEIGHT HDL_PARAMETER true
add_parameter VGA_INPUT_STREAM_WIDTH INTEGER 8 ""
set_parameter_property VGA_INPUT_STREAM_WIDTH DEFAULT_VALUE 8
set_parameter_property VGA_INPUT_STREAM_WIDTH DISPLAY_NAME VGA_INPUT_STREAM_WIDTH
set_parameter_property VGA_INPUT_STREAM_WIDTH TYPE INTEGER
set_parameter_property VGA_INPUT_STREAM_WIDTH UNITS None
set_parameter_property VGA_INPUT_STREAM_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property VGA_INPUT_STREAM_WIDTH DESCRIPTION ""
set_parameter_property VGA_INPUT_STREAM_WIDTH HDL_PARAMETER true
add_parameter VGA_OUTPUT_STREAM_WIDTH INTEGER 16
set_parameter_property VGA_OUTPUT_STREAM_WIDTH DEFAULT_VALUE 16
set_parameter_property VGA_OUTPUT_STREAM_WIDTH DISPLAY_NAME VGA_OUTPUT_STREAM_WIDTH
set_parameter_property VGA_OUTPUT_STREAM_WIDTH TYPE INTEGER
set_parameter_property VGA_OUTPUT_STREAM_WIDTH UNITS None
set_parameter_property VGA_OUTPUT_STREAM_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property VGA_OUTPUT_STREAM_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true

add_interface_port clock clk_cpu clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset reset_n reset_n Input 1


# 
# connection point fifoin
# 
add_interface fifoin avalon_streaming end
set_interface_property fifoin associatedClock clock_video
set_interface_property fifoin associatedReset reset
set_interface_property fifoin dataBitsPerSymbol 8
set_interface_property fifoin errorDescriptor ""
set_interface_property fifoin firstSymbolInHighOrderBits true
set_interface_property fifoin maxChannel 0
set_interface_property fifoin readyLatency 0
set_interface_property fifoin ENABLED true

add_interface_port fifoin asi_fifoin_ready ready Output 1
add_interface_port fifoin asi_fifoin_data data Input vga_input_stream_width
add_interface_port fifoin asi_fifoin_startofpacket startofpacket Input 1
add_interface_port fifoin asi_fifoin_endofpacket endofpacket Input 1
add_interface_port fifoin asi_fifoin_valid valid Input 1


# 
# connection point vgaout
# 
add_interface vgaout avalon_streaming start
set_interface_property vgaout associatedClock clock_video
set_interface_property vgaout associatedReset reset
set_interface_property vgaout dataBitsPerSymbol 16
set_interface_property vgaout errorDescriptor ""
set_interface_property vgaout firstSymbolInHighOrderBits true
set_interface_property vgaout maxChannel 0
set_interface_property vgaout readyLatency 0
set_interface_property vgaout ENABLED true

add_interface_port vgaout aso_vgaout_ready ready Input 1
add_interface_port vgaout aso_vgaout_data data Output vga_output_stream_width
add_interface_port vgaout aso_vgaout_startofpacket startofpacket Output 1
add_interface_port vgaout aso_vgaout_endofpacket endofpacket Output 1
add_interface_port vgaout aso_vgaout_valid valid Output 1


# 
# connection point paletteram
# 
add_interface paletteram avalon end
set_interface_property paletteram addressUnits WORDS
set_interface_property paletteram associatedClock clock
set_interface_property paletteram associatedReset reset
set_interface_property paletteram bitsPerSymbol 8
set_interface_property paletteram burstOnBurstBoundariesOnly false
set_interface_property paletteram burstcountUnits WORDS
set_interface_property paletteram explicitAddressSpan 0
set_interface_property paletteram holdTime 0
set_interface_property paletteram linewrapBursts false
set_interface_property paletteram maximumPendingReadTransactions 0
set_interface_property paletteram readLatency 0
set_interface_property paletteram readWaitTime 1
set_interface_property paletteram setupTime 0
set_interface_property paletteram timingUnits Cycles
set_interface_property paletteram writeWaitTime 0
set_interface_property paletteram ENABLED true

add_interface_port paletteram avs_paletteram_read_n read_n Input 1
add_interface_port paletteram avs_paletteram_readdata readdata Output 32
add_interface_port paletteram avs_paletteram_address address Input 4
add_interface_port paletteram avs_paletteram_write_n write_n Input 1
add_interface_port paletteram avs_paletteram_writedata writedata Input 32
set_interface_assignment paletteram embeddedsw.configuration.isFlash 0
set_interface_assignment paletteram embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment paletteram embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment paletteram embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_video
# 
add_interface clock_video clock end
set_interface_property clock_video clockRate 0
set_interface_property clock_video ENABLED true

add_interface_port clock_video clk_video clk Input 1

