# TCL File Generated by Component Editor 12.1sp1
# Sun Jan 31 09:53:01 MST 2016
# DO NOT MODIFY


# 
# video_fb_streamer "video_fb_streamer" v1.0
# null 2016.01.31.09:53:01
# 
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module video_fb_streamer
# 
set_module_property NAME video_fb_streamer
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME video_fb_streamer
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL video_fb_streamer
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file video_fb_streamer.vhd VHDL PATH video_fb_streamer/video_fb_streamer.vhd


# 
# parameters
# 
add_parameter BUFFER_START_ADDRESS STD_LOGIC_VECTOR 0
set_parameter_property BUFFER_START_ADDRESS DEFAULT_VALUE 0
set_parameter_property BUFFER_START_ADDRESS DISPLAY_NAME BUFFER_START_ADDRESS
set_parameter_property BUFFER_START_ADDRESS WIDTH 32
set_parameter_property BUFFER_START_ADDRESS TYPE STD_LOGIC_VECTOR
set_parameter_property BUFFER_START_ADDRESS UNITS None
set_parameter_property BUFFER_START_ADDRESS ALLOWED_RANGES 0:4294967295
set_parameter_property BUFFER_START_ADDRESS HDL_PARAMETER true
add_parameter BITS_PER_PIXEL INTEGER 8
set_parameter_property BITS_PER_PIXEL DEFAULT_VALUE 8
set_parameter_property BITS_PER_PIXEL DISPLAY_NAME BITS_PER_PIXEL
set_parameter_property BITS_PER_PIXEL TYPE INTEGER
set_parameter_property BITS_PER_PIXEL UNITS None
set_parameter_property BITS_PER_PIXEL ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BITS_PER_PIXEL HDL_PARAMETER true
add_parameter FRAME_WIDTH INTEGER 640
set_parameter_property FRAME_WIDTH DEFAULT_VALUE 640
set_parameter_property FRAME_WIDTH DISPLAY_NAME FRAME_WIDTH
set_parameter_property FRAME_WIDTH TYPE INTEGER
set_parameter_property FRAME_WIDTH UNITS None
set_parameter_property FRAME_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FRAME_WIDTH HDL_PARAMETER true
add_parameter FRAME_HEIGHT INTEGER 480
set_parameter_property FRAME_HEIGHT DEFAULT_VALUE 480
set_parameter_property FRAME_HEIGHT DISPLAY_NAME FRAME_HEIGHT
set_parameter_property FRAME_HEIGHT TYPE INTEGER
set_parameter_property FRAME_HEIGHT UNITS None
set_parameter_property FRAME_HEIGHT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FRAME_HEIGHT HDL_PARAMETER true


# 
# display items
# 


# 
# connection point conduit_end_0
# 
add_interface conduit_end_0 conduit end
set_interface_property conduit_end_0 associatedClock clock_sink
set_interface_property conduit_end_0 associatedReset reset_sink
set_interface_property conduit_end_0 ENABLED true

add_interface_port conduit_end_0 coe_swap_frame export Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock_sink
set_interface_property avalon_master associatedReset reset_sink
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true

add_interface_port avalon_master avm_dma0_readdata readdata Input 16
add_interface_port avalon_master avm_dma0_readdatavalid readdatavalid Input 1
add_interface_port avalon_master avm_dma0_waitrequest waitrequest Input 1
add_interface_port avalon_master avm_dma0_address address Output 32
add_interface_port avalon_master avm_dma0_read read Output 1
add_interface_port avalon_master avm_dma0_burstcount burstcount Output 8


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true

add_interface_port clock_sink clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true

add_interface_port reset_sink reset reset Input 1


# 
# connection point source
# 
add_interface source avalon_streaming start
set_interface_property source associatedClock clock_sink
set_interface_property source associatedReset reset_sink
set_interface_property source dataBitsPerSymbol 8
set_interface_property source errorDescriptor ""
set_interface_property source firstSymbolInHighOrderBits true
set_interface_property source maxChannel 0
set_interface_property source readyLatency 0
set_interface_property source ENABLED true

add_interface_port source aso_source_data data Output bits_per_pixel
add_interface_port source aso_source_endofpacket endofpacket Output 1
add_interface_port source aso_source_startofpacket startofpacket Output 1
add_interface_port source aso_source_valid valid Output 1
add_interface_port source aso_source_ready ready Input 1

